### ISSUE TITLE
NullPointerException while using the IDE

### ISSUE THREAD

**Issue by Davoleo** [mallowigi/material-theme-ui-lite#2]
Stacktrace: https://pastebin.com/afE1k8yx
OS: Window 10

**Comment by mbranicky** [comment]
Getting the same NPE at the same exact place.

=== About ===
Build version: IntelliJ IDEA 2019.2.3 Build #IU-192.6817.14 September 24, 2019
Java version: 11.0.4+10-b304.69x86_64
Operating System: Mac OS X (10.14.6, x86_64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o

=== System ===
Number of CPU: 8
Used memory: 326Mb 
Free memory: 134Mb 
Total memory: 461Mb 
Maximum available memory: 1955Mb

=== Displays ===
Displays: 
Display 0: 1920x1200; scale: 1,00
Display 1: 1200x1920; scale: 1,00
Display 2: 3840x2400; scale: 2,00

=== Plugins ===
Custom plugins: [Assets Compressor (1.2.1), Vuesion Theme (1.8), Ini (192.6262.16), File Watchers (192.6603.8), Material Theme UI Lite (4.0), .ignore (3.2.2.192), AsciiDoc (0.30.7), BashSupport (1.7.13.192), Handlebars/Mustache (192.6262.9), Vue.js (192.6262.27), Python (2019.2.192.6817.14), GitToolBox (192.3.0)]
Disabled plugins:[Batch Scripts Support (1.0.7), OpenShift integration (192.6817.14), Perforce (192.6817.14), SvgViewer 2 (2.1), ZKM-Unscramble (192.6817.14), Smali Support (192.6817.14), Nord (0.5.0), Copyright (192.6817.14), Reactor (192.6817.14), UML (192.6817.14), Guice (192.6817.14), TestNG (192.6817.14), Emma (192.6817.14), Time Tracking (192.6817.14), UI Designer (192.6817.14), Velocity (192.6817.14), ASP (192.6817.14), Remote Hosts Access (192.6817.14), Gradianto (3.2), Gherkin (192.6817.14), Cucumber for Java (192.6817.14), Markdown (0.9.7), CFML (192.6817.14), GlassFish (192.6817.14), Heroku (192.6817.14), WildFly (192.6817.14), Jetty Integration (192.6817.14), Resin Integration (192.6817.14), Geronimo Integration (192.6817.14), WebSphere Integration (192.6817.14), WebLogic Integration (192.6817.14), JBoss Frameworks Base (192.6817.14), Drools (192.6817.14), Arquillian (192.6817.14), JBoss jBPM (192.6817.14), Tapestry (192.6817.14), Markdown Navigator (2.1.1), Groovy (192.6817.14), Play Framework (192.6817.14), Cucumber for Groovy (192.6817.14), Android Support (10.3.4), Eclipse Interoperability (192.6817.14), Gradle Integration Extension (192.6817.14), OSGi (192.6817.14), GitHub (192.6817.14), Gradle (192.6817.14), Plugin DevKit (192.6817.14), Gradle-Maven (192.6817.14), Haml (192.6817.14), JavaFX (192.6817.14), Kotlin (1.3.41-release-IJ2019.2-1), EduTools (2.5-2019.1-1540), Flash/Flex (192.6817.14), JBoss Seam (192.6817.14), JBoss Seam Pageflow (192.6817.14), JBoss Seam Pages (192.6817.14), Cloud Foundry (192.6817.14), Virgo/dmServer (192.6817.14), FreeMarker (192.6817.14), Google App Engine (192.6817.14), Struts 2 (192.6817.14), Thymeleaf (192.6817.14), HTTP Client (192.6817.14), CoffeeScript (192.6817.14), Grails (192.6817.14), SSH Remote Run (192.6817.14), Docker (192.6817.14), Spy-js (192.6817.14), Angular and AngularJS (192.6817.14)]

**Comment by mallowigi** [comment]
Will be fixed in v5.0

**Comment by Luladjiev** [comment]
Using v6.0 of the plugin and have this exception occurred also one with a bit different stack trace:

https://pastebin.com/m0Xs8jpr
https://pastebin.com/QzCGc7cV

WebStorm 2019.3
Build #WS-193.5233.80, built on November 25, 2019
Runtime version: 11.0.4+10-b520.11 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.3.12-1-default
GC: ParNew, ConcurrentMarkSweep
Memory: 1092M
Cores: 4
Registry: ide.intellij.laf.enable.animation=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.mallowigi.idea

**Comment by mbranicky** [comment]
I am also getting NPE in plugin version 6.0:

https://pastebin.com/WdZ65DsB

Build version: IntelliJ IDEA 2019.3 Build #IU-193.5233.102 November 27, 2019
Java version: 11.0.4+10-b520.11amd64
Operating System: Windows 10 (10.0, amd64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o
Number of CPU: 12
Used memory: 520Mb 
Free memory: 437Mb 
Total memory: 958Mb 
Maximum available memory: 1956Mb

**Comment by advicepyro** [comment]
@mallowigi will this be fixed in an upcoming release? On 7.0 it continues to throw a NullPointerException at MTAbstractThemeAction.java:73.

Build info:

PhpStorm 2019.3.1
Build #PS-193.5662.63, built on December 19, 2019
Runtime version: 11.0.5+10-b520.17 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.2
GC: ParNew, ConcurrentMarkSweep
Memory: 1502M
Cores: 4
Registry: ide.intellij.laf.enable.animation=true, run.processes.with.pty=TRUE, debugger.watches.in.variables=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: BashSupport, com.mallowigi.idea, ru.adelf.idea.dotenv

**Comment by mallowigi** [comment]
There was typos in the themes, maybe it was the reason of the npe. I’ve released 7.2 so please download it when it is available and tell me if the error is gone.

**Comment by advicepyro** [comment]
@mallowigi NPEs are still occurring. Two stack traces below:

```
java.lang.NullPointerException
	at com.mallowigi.idea.themes.MTAbstractThemeAction.getThemeName(MTAbstractThemeAction.java:73)
	at com.mallowigi.idea.themes.MTAbstractThemeAction.isSelected(MTAbstractThemeAction.java:60)
	at com.intellij.ide.util.gotoByName.GotoActionModel$GotoActionListCellRenderer.getListCellRendererComponent(GotoActionModel.java:765)
	at com.intellij.ide.actions.searcheverywhere.SearchEverywhereUI$CompositeCellRenderer.getListCellRendererComponent(SearchEverywhereUI.java:956)
	at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:38)
	at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:38)
	at com.intellij.ui.components.WideSelectionListUI.updateLayoutState(WideSelectionListUI.java:150)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1389)
	at java.desktop/javax.swing.plaf.basic.BasicListUI$Handler.valueChanged(BasicListUI.java:2785)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:219)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:199)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:246)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:443)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:453)
	at java.desktop/javax.swing.DefaultListSelectionModel.addSelectionInterval(DefaultListSelectionModel.java:556)
	at java.desktop/javax.swing.JList.setSelectedIndices(JList.java:2230)
	at com.intellij.ide.actions.searcheverywhere.SEListSelectionTracker.restoreSelection(SEListSelectionTracker.java:73)
	at com.intellij.ide.actions.searcheverywhere.SearchEverywhereUI$SearchListener.elementsAdded(SearchEverywhereUI.java:1565)
	at com.intellij.ide.actions.searcheverywhere.ThrottlingListenerWrapper.lambda$null$0(ThrottlingListenerWrapper.java:38)
	at com.intellij.ide.actions.searcheverywhere.ThrottlingListenerWrapper.lambda$new$2(ThrottlingListenerWrapper.java:38)
	at com.intellij.ide.actions.searcheverywhere.ThrottlingListenerWrapper$Buffer.flush(ThrottlingListenerWrapper.java:131)
	at com.intellij.ide.actions.searcheverywhere.ThrottlingListenerWrapper.searchFinished(ThrottlingListenerWrapper.java:69)
	at com.intellij.ide.actions.searcheverywhere.MultiThreadSearcher$FullSearchResultsAccumulator.lambda$searchFinished$6(MultiThreadSearcher.java:412)
	at com.intellij.ide.actions.searcheverywhere.MultiThreadSearcher$ResultsAccumulator.lambda$runInNotificationExecutor$1(MultiThreadSearcher.java:264)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:309)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

```
java.lang.NullPointerException
	at com.mallowigi.idea.themes.MTAbstractThemeAction.getThemeName(MTAbstractThemeAction.java:73)
	at com.mallowigi.idea.themes.MTAbstractThemeAction.isSelected(MTAbstractThemeAction.java:60)
	at com.intellij.ide.util.gotoByName.GotoActionModel$GotoActionListCellRenderer.getListCellRendererComponent(GotoActionModel.java:765)
	at com.intellij.ide.actions.searcheverywhere.SearchEverywhereUI$CompositeCellRenderer.getListCellRendererComponent(SearchEverywhereUI.java:956)
	at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:38)
	at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:38)
	at com.intellij.ui.components.WideSelectionListUI.updateLayoutState(WideSelectionListUI.java:150)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1389)
	at java.desktop/javax.swing.plaf.basic.BasicListUI$Handler.valueChanged(BasicListUI.java:2785)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:219)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:199)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:246)
	at java.desktop/javax.swing.DefaultListSelectionModel.insertIndexInterval(DefaultListSelectionModel.java:670)
	at java.desktop/javax.swing.plaf.basic.BasicListUI$Handler.intervalAdded(BasicListUI.java:2743)
	at java.desktop/javax.swing.AbstractListModel.fireIntervalAdded(AbstractListModel.java:153)
	at com.intellij.ide.actions.searcheverywhere.SearchEverywhereUI$SearchListModel.applyChange(SearchEverywhereUI.java:1187)
	at com.intellij.ide.actions.searcheverywhere.SearchEverywhereUI$SearchListModel.lambda$addElements$6(SearchEverywhereUI.java:1104)
	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
	at com.intellij.ide.actions.searcheverywhere.SearchEverywhereUI$SearchListModel.addElements(SearchEverywhereUI.java:1097)
	at com.intellij.ide.actions.searcheverywhere.SearchEverywhereUI$SearchListener.elementsAdded(SearchEverywhereUI.java:1562)
	at com.intellij.ide.actions.searcheverywhere.ThrottlingListenerWrapper.lambda$null$0(ThrottlingListenerWrapper.java:38)
	at com.intellij.ide.actions.searcheverywhere.ThrottlingListenerWrapper.lambda$new$2(ThrottlingListenerWrapper.java:38)
	at com.intellij.ide.actions.searcheverywhere.ThrottlingListenerWrapper$Buffer.flush(ThrottlingListenerWrapper.java:131)
	at com.intellij.ide.actions.searcheverywhere.ThrottlingListenerWrapper.searchFinished(ThrottlingListenerWrapper.java:69)
	at com.intellij.ide.actions.searcheverywhere.MultiThreadSearcher$FullSearchResultsAccumulator.lambda$searchFinished$6(MultiThreadSearcher.java:412)
	at com.intellij.ide.actions.searcheverywhere.MultiThreadSearcher$ResultsAccumulator.lambda$runInNotificationExecutor$1(MultiThreadSearcher.java:264)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:309)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by mallowigi** [comment]
A new version (7.3) has been released. Please try it.
